spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true

  redis:
    host: localhost
    port: 6379
